---

- hosts: all
  become: true
  tasks:

# Update repos and installs apache and php

  - name: install apache2 and php packages
    package:
      update_cache: yes 
      name: 
        - "{{apache_pkg}}" 
        - "{{php_pkg}}"
      state: latest
